### ISSUE TITLE
A non-numeric value

### ISSUE THREAD

**Issue by oliviermaridat** [dmorlitz/kanboard-CardPushDate#11]
Thanks a lot for the plugin!

I just got a bug on my KB instance recently. From what I know, nothing has changed and then it appears one day. Since this is not possible, I suppose this is due to an update on server side (PHP version?) or on the KB config related to meta data.

In any case, I got this error:
![image](https://github.com/dmorlitz/kanboard-CardPushDate/assets/953989/2f5c22ab-26a4-440b-8127-be15456e7833)

I fixed that by using `intval` on `$CardPushData_interval_Monday` which appeared to be a string:

task_private.php around line130:

```
<?php //Add a line break if a due date is set and we are displaying any push buttons
                       if ( (intval($CardPushDate_interval_Monday) +
                             $CardPushDate_interval_1 +
                             $CardPushDate_interval_2 +
                             $CardPushDate_interval_3 > 0) && (! empty($task['date_due'])) )
                             {
                                echo "<br>";
                             }
                 ?>

	         <?php if (intval($CardPushDate_interval_Monday) > 0): ?>
```

**Comment by dmorlitz** [comment]
I am glad that this code has helped you.  I don't actually have a working Kanboard installation any longer - so I have not made any updates to this code.  If you want to submit a Pull request, I would accept it.  If you would prefer to take over this repository, I would accept that as well.

**Comment by oliviermaridat** [comment]
I can submit a PR with pleasure. I just did that very quickly and did not check if my fix made any sense ^^ If you think it make sense, I can submit one.

**Comment by rafacamargo123** [comment]
I've proposed the fix in a different manner, the same way it was done for the other settings:
https://github.com/dmorlitz/kanboard-CardPushDate/blob/544f8b8d85473ae40baa61df9d3b8428be91d65f/Template/layout/task/task_private.php#L106-L111
