### ISSUE TITLE
Can't send comments with icon on card since Kanboard 1.2.36

### ISSUE THREAD

**Issue by mariohommel** [dmorlitz/kanboard-CardPushDate#12]
The new version of Kanboard 1.2.36 brings some new feature to comments.

The comment icon on a card provided by CardPushDate doesn't work anymore. You can fill in the comment text but pressing the "Save"-Button does nothing.

**Comment by mariohommel** [comment]
This is fixed here: https://github.com/kanboard/kanboard/commit/50b5362c7890751e588cc1179aceec4d4974a172

**Comment by dmorlitz** [comment]
Thank you very much for the fix.  Just so you are aware, I am no longer using Kamboard, so I have stopped supporting this plugin.  I would be happy to transfer the repo to anyone else that it interested in providing ongoing support.....just let me know.
