### ISSUE TITLE
( ! ) Warning: Undefined array key "CardPushDate_interval_1_randomize" 

### ISSUE THREAD

**Issue by DangerDrome** [dmorlitz/kanboard-CardPushDate#14]
```

( ! ) Warning: Undefined array key "CardPushDate_interval_1_randomize"

```
---

# Getting errors in:
### CardPushSettingsController.php

**Comment by dmorlitz** [comment]
I am no longer maintaining this code - as I am not currently using Kanboard for my projects.  If you want to take over this code, I am happy to transfer this repo to you - or you can create your own fork and I will point this one to it.
