### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by grayed** [dmorlitz/kanboard-CardPushDate#5]
Is a new release planned? A lot of water flowed since the April 2018... :) Or should we (users) just clone the repo and be done with it?

**Comment by dmorlitz** [comment]
Is something not working?  If so, I will try to get it fixed.  I am still
running the same code on my current Kanboard (which I update regularly) and
I have not noticed any problems.

**Comment by grayed** [comment]
The current "master" code works fine, it's just a matter of having formal release, or not. The 1.0 release was 1.5 years and 30 (out of 41) commits ago. :) I'm not forcing you, just willing to clarify the way you recommend to install the plugin.

**Comment by dmorlitz** [comment]
As you can tell - I am not a GitHub expert.  Let me package up a new
version right now with all of the latest commits so everything stays in
sync.

**Comment by grayed** [comment]
Thank you very much!
