### ISSUE TITLE
Show last comment on card - always shows comments

### ISSUE THREAD

**Issue by SantaClaus0912** [dmorlitz/kanboard-CardPushDate#6]
Hi,
I have installed Kanboard Version: 1.2.11 and Version 1.0 of this plugin.
The buttons to push the date are working fine, but the checkbox in the settings for "Show last comment on card" is not working. 
Independend if it´s activated or not, the card always shows the last comment.

1) Can that be checked? Any ideas how to tackle that?
2) Can the length of the shown comment be limited? Sometimes the comments are quite long and the card get´s really big.

Other installed plugins:

- KanboardCommentActions
- Gantt
- Meilenstein
- SubtaskDueDate
- Theme Plus
- Customizer
- Auto Email Extended Actions

![card](https://user-images.githubusercontent.com/14799787/71076235-a755b380-2185-11ea-99cb-d290dcc10880.JPG)
![settings](https://user-images.githubusercontent.com/14799787/71076236-a7ee4a00-2185-11ea-95be-31c67ec41c4a.JPG)

Thanks,

SantaClaus

**Comment by dmorlitz** [comment]
You are definitely correct - there was a glitch in the display logic.
Apparently when I changed how I store configuration, I missed that update.
Comments should now follow the settings in the config panel.  You should be
able to set the visibility of comments in both the expanded and collapsed
view separately as well.

It would be possible to add another config setting to limit the length of
the comments.  I wouldn't have time to look at that for about 2 weeks (or
so) but I will try to remember to look into that.  It is a good idea -
thank you.

**Comment by SantaClaus0912** [comment]
Thank you very much for your super fast response! Problem is solved. I would be happy if you can think about limiting the comment on the card, but not urgent for me. Maybe you can mark it as a feature request.
Best regards
