### ISSUE TITLE
feature request: trim due date 

### ISSUE THREAD

**Issue by kworr** [dmorlitz/kanboard-CardPushDate#7]
Hello.

Right now I'm using Calendar export extensively. In calendar all tasks with time set are shown on specific time, and I want them to be "All day" tasks. If original due date is set to some date with time at 00:00 everything looks fine. But when I push task it receives current time and is scheduled for specific time. May I ask for an option to set new date without setting time or cropping time to 00:00?

Thanks in advance.

PS: This plugin rocks, I was trying to get the same behavior in Trello/Asana and it's not even close to be that easy to maintain.

**Comment by dmorlitz** [comment]
I have just pushed a new version.  Please take a look at it and let me know
what you think.

I have added a text entry field to the settings panel that will let you
specify a time for the pushed events.  If you leave the box empty it will
assume 00:00.  If you enter an invalid 24-hour format time when you save
the time it will be forced to 00:01.  Other than that, I hope it works.

I don't use an exported calendar so I haven't done a whole lot of testing.
I did check with the time that Kanboard shows and I think this works as
expected.

If you encounter any problems please let me know and I will see what I can
do.

Also - just as a reminder - the settings are board specific.  You should be
able to specify different times on each board, if you want.  The code will
also assume 00:00 if you don't have a time set so currently none of your
boards have a time set, so they will all default to 00:00

**Comment by kworr** [comment]
Thank you! Works perfectly.
